version: "3"
services:
  raft-1:
    build: .
    environment:
      CLUSTER_MEMBERS: 1@raft-1:8080,2@raft-2:8080,3@raft-3:8080
    command: -id=1
    ports:
      - "8081:8080"
  raft-2:
    build: .
    environment:
      CLUSTER_MEMBERS: 1@raft-1:8080,2@raft-2:8080,3@raft-3:8080
    command: -id=2
    ports:
      - "8082:8080"
  raft-3:
    build: .
    environment:
      CLUSTER_MEMBERS: 1@raft-1:8080,2@raft-2:8080,3@raft-3:8080
    command: -id=3
    ports:
      - "8083:8080"
